// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace JPSportsApi.Infrastructure.Persistence.CompiledModels
{
    public partial class JPSportsDbContextModel
    {
        private JPSportsDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("6f2e5999-6024-4c5f-8734-329b46d154c1"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var team = TeamEntityType.Create(this);

            TeamEntityType.CreateAnnotations(team);

            AddAnnotation("ProductVersion", "10.0.7");
        }
    }
}
