// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace JPSportsApi.Infrastructure.Persistence.CompiledModels
{
    public partial class JPSportsDbContextModel
    {
        private JPSportsDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("c9c68b3d-0f91-4836-9aaf-81f1bd48ce82"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var team = TeamEntityType.Create(this);

            TeamEntityType.CreateAnnotations(team);

            AddAnnotation("ProductVersion", "10.0.7");
        }
    }
}
