// <auto-generated />
using JPSportsApi.Infrastructure.Persistence;
using JPSportsApi.Infrastructure.Persistence.CompiledModels;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(JPSportsDbContext), typeof(JPSportsDbContextModel))]
